[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "klava"
version = "0.2.1"
authors = [
  { name = "Iurii Zatsepin", email = "support@zatsepin.dev" },
]
description = "Klava is a CLI tool for using code agents with any provider. Use Claude Code with your OpenAI-compatible provider. Make code agents more secure by filtering out leaked secret keys and cryptographic keys from your filesystem."
readme = "README.md"
keywords = ["anthropic", "openai", "proxy", "claude", "api"]
license = { file = "LICENSE" }
classifiers = [
  "Environment :: Console",
  "Programming Language :: Rust",
  "Topic :: Text Processing",
]

[project.urls]
Homepage = "https://github.com/Partysun/klava"
Repository = "https://github.com/Partysun/klava"
Documentation = "https://github.com/Partysun/klava#readme"

[tool.maturin]
bindings = "bin"
manifest-path = "Cargo.toml"
strip = true
locked = true
