when:
  - event: [deployment, tag]

labels:
  platform: linux/amd64

steps:
  - name: publish
    image: ghcr.io/pyo3/maturin
    commands:
      - pip install uv
      - maturin build --release --manylinux 2_17 --out dist
      - ls -l dist/ && ls -l
      - uv publish --token $${UV_TOKEN} dist/*
    environment:
      UV_TOKEN:
        from_secret: uv_token
