when:
  - event: deployment
    evaluate: '(CI_PIPELINE_DEPLOY_TASK ?? "") in ["", "linux", "publish"]'
  - event: tag
    ref: refs/tags/v*

labels:
  backend: docker
  platform: linux/amd64

steps:
  - name: publish
    image: ghcr.io/pyo3/maturin
    commands:
      - pip install uv
      - maturin build --release --manylinux 2_17 --sdist --out dist
      - uv publish dist/*
    environment:
      UV_PUBLISH_TOKEN:
        from_secret: uv_token