when:
  - event: [push, pull_request]
    branch: master
  - event: manual

labels:
  backend: docker
  platform: linux/amd64

steps:
  - name: test
    image: rust:latest
    commands:
      - cargo test

  - name: build
    image: ghcr.io/pyo3/maturin
    commands:
      - maturin build --release --manylinux 2_17 --sdist --out dist
    depends_on:
      - test
